#!/bin/bash
# NEXTFLOW TASK: archiveResults
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /home/purav/Projects/bioinformatics-pipeline-tutorial/work/b1/d9a9999c66379ed8e5c59c96b8188f/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/purav/Projects/bioinformatics-pipeline-tutorial/work/b1/d9a9999c66379ed8e5c59c96b8188f/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f PO5F1.plot.png
    rm -f SOX2.plot.png
    rm -f MYC.plot.png
    rm -f KLF4.plot.png
    rm -f protein_report.tsv
    ln -s /home/purav/Projects/bioinformatics-pipeline-tutorial/work/ce/1b4978ab832b4263ab9b5fcedb62a9/PO5F1.plot.png PO5F1.plot.png
    ln -s /home/purav/Projects/bioinformatics-pipeline-tutorial/work/c2/a9362694884ae7707798f4f7858fb3/SOX2.plot.png SOX2.plot.png
    ln -s /home/purav/Projects/bioinformatics-pipeline-tutorial/work/25/959e80b17c3a294483ecce7857bf2c/MYC.plot.png MYC.plot.png
    ln -s /home/purav/Projects/bioinformatics-pipeline-tutorial/work/b1/bd58d9d07da8cf755004524cb2c666/KLF4.plot.png KLF4.plot.png
    ln -s /home/purav/Projects/bioinformatics-pipeline-tutorial/work/be/d106d426afea4e1da64844f9f7957f/protein_report.tsv protein_report.tsv
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/purav/Projects/bioinformatics-pipeline-tutorial/work/b1/d9a9999c66379ed8e5c59c96b8188f/.command.begin
    set +u
    set -u
    export PATH="$PATH:/home/purav/Projects/bioinformatics-pipeline-tutorial/bin"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
